services:
  web:
    container_name: web_test-idx
    image: globaldigitalagency/sample:8.3
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.test-idx.rule=Host(`test-idx.wsl`)"
      - "traefik.http.routers.test-idx.entrypoints=web"
      # https
      - "traefik.http.routers.test-idx_https.tls=true"
      - "traefik.http.routers.test-idx_https.rule=Host(`test-idx.wsl`)"
      - "traefik.http.routers.test-idx_https.entrypoints=websecure"
    volumes:
      - .:/var/www
      - ./.docker/vhosts:/etc/apache2/sites-enabled
      - ../dev-tools/aliases/.bash_global.sh:/.bash_global.sh
      - ../dev-tools/aliases/.bash_global_perso.sh:/.bash_global_perso.sh
    networks:
      - traefik-net
    # extra host for xdebug
    extra_hosts:
      - host.docker.internal:host-gateway


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  traefik-net:
    external: true
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
